version: '3'
services:
    nginx:
        image: staticfloat/nginx-certbot
        restart: always
        ports:
            - "80:80"
            - "444:443"
        environment: 
            CERTBOT_EMAIL: test@test.test       
            ENVSUBST_VARS: FQDN
            FQDN: test.test.test                
        volumes:
            - ./nginx:/etc/nginx/user.conf.d
            - letsencrypt:/etc/letsencrypt
    v2ray:
        image: v2fly/v2fly-core:latest
        network_mode: host
        restart: always
        ports: 
            - "443:443"
        volumes:
            - ./v2ray:/etc/v2ray
            - letsencrypt:/etc/letsencrypt
volumes:
    letsencrypt: